### ISSUE TITLE
regolith-i3 4.16-1ubuntu18ppa10 seems to be pulling config from wrong file

### ISSUE THREAD

**Issue by the-neo-zeed** [regolith-linux/regolith-i3#10]
I just updated to `4.16-1ubuntu18ppa10` and immediately noticed the old config `~/.config/i3-regolith/config` isn't being used. It's pulling from `~/.config/i3-regolith/config-4.16-1ubuntu18ppa10` instead. I renamed the old config to the new name to get my customizations back.

**Comment by the-neo-zeed** [comment]
I also noticed in `~` there are two Xresources files:
- `.Xresources-regolith`
- `.Xresources-regolith-1.2.15`

Is this by design? Will each update create new config files with the version number of the package appended to the name?

**Comment by kgilmer** [comment]
Hi @the-neo-zeed , yes this is by design and it's a new feature as of yesterday.  It's safe to delete the `Xresources-regolith` file if it doesn't have anything you need.  Going forward both the i3 config and the Xresources root file will be versioned.  This approach is used because in some cases there are breaking changes that need updates to user's config files.  However, it's not cool to just overwrite whatever is on disk.  This strategy allows me to ensure compatible config files are loaded and allow users the ability of merging their changes back in.  Overall, most configuration should be pushed into the Xresources file, which should make it easy to merge back changes as needed.  

There is a flag you can enable that will prevent Regolith from mapping your configuration to new values, and is documented here: https://regolith-linux.org/configuring.html

If you have concerns or suggestions please let me know :smile:

**Comment by kgilmer** [comment]
Also, you may want to diff your configuration with ~/.config/i3-regolith/config-4.16-1ubuntu18ppa10 if you'd like to be able to change your configuration via Xresources.

**Comment by illixion** [comment]
So where do I put my i3 configuration now? I've just upgraded my Regolith install and all of my custom settings seem to be gone.

**Comment by Walms** [comment]
Thanks for all your work on this distro, it's really nice to have an ubuntu that ships with I3

Just to let you know the impact this versioning has on some users. I upgraded today. After a reboot I was unable to use my computer. The new config file defaults the Windows key as the modifier. I have a keyboard that, while it's great at preventing RSI it lacks some keys, the Windows key for one. 
So I was unable to use I3 until I located the new file and changed the mod key back to the alt key. 

Now that I know how to resolve this it's no issue I can get past it. I should have read the docs more but it's not the nicest experience to have your configs overwritten like this in an update.

**Comment by kgilmer** [comment]
Hi @Walms , thanks for your feedback.  I agree that breaking changes need to be handled in a better way.  Another person affected by the recent Xresources change suggested a mailing list for project updates and I think it's a good idea.  I'll create that, add it to the site, and give some notice before pushing updates that will cause users to have to bump their package versions, although I hope this will be rare.
